version: '3.7'

networks: 
    application:
        name: allinpay-backend
        driver: bridge
    database:
        external: true
services: 
### NGINX Server #########################################
    nginx:
        image: "nginx:1.17.4"
        volumes:
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
        ports: 
            - "${NGINX_HOST_HTTP_PORT}:80"
        networks:
            - application
            - database
        container_name: allinpay-nginx
### MYSQL ################################################
    mysql:
        image: "registry.cn-hangzhou.aliyuncs.com/unintell/mysql:1.0.0"
        environment: 
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - TZ=${MYSQL_TIMEZONE}
        volumes: 
            - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
            - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
        ports:
            - "${MYSQL_PORT}:3306"
        networks:
            - application
            - database
        container_name: allinpay-mysql
### Redis #################################################
    redis:
        image: "redis:latest"
        volumes: 
            - ${DATA_PATH_HOST}/redis:/data
        ports:
            - "${REDIS_PORT}:6379"
        networks: 
            - application
            - database
        container_name: allinpay-redis
### mongo #################################################
    mongo:
        image: "mongo"
        environment:
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        volumes:
            # wsl下文件权限问题 windows下数据可持久化
            # https://github.com/docker-library/mongo/issues/74
            # - ${DATA_PATH_HOST}/mongo:/data/db
            - ${MONGO_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
        ports:
            - ${MONGO_PORT}:27017
        networks:
            - application
            - database
        container_name: allinpay-mongo
